spring.application.name=assuflex-api
spring.datasource.url=jdbc:postgresql://localhost:5432/assuflex
spring.datasource.password=123456789
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# NIDHAL SPRING BOOT SOME PARAMS FOR BEST DEVS ENV
spring.main.banner-mode=off
logging.level.root=ERROR
logging.level.org.springframework=ERROR
spring.main.log-startup-info=false

# SETUP AND CONFIG FOR GOOGLE SMTP todo -//lezem ba3d ttbadl fi l production

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nidhalsaddouri33@gmail.com
spring.mail.password=zsgc uwcz wltj hlby
logging.level.org.springframework.mail=ERROR

spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# optional timeouts
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000

#stripe
stripe.success.url=http://localhost:8080/api/payments/success
stripe.cancel.url=http://localhost:8080/api/payments/payment-cancel